site_name: Solo Technical Documentation
site_author: SoloKeys
site_description: 'Documentation for the SoloKeys solo software'
site_url: 'https://docs.solokeys.io/solo/'
repo_url: 'https://github.com/solokeys/solo'
repo_name: 'solokeys/solo'
copyright: 'Copyright &copy; 2018 - 2019 SoloKeys'

nav:
    - Home: solo/index.md
    - FIDO2 Implementation: solo/fido2-impl.md
    - Build instructions: solo/building.md
    - Running on Nucleo32 board: solo/nucleo32-board.md
    - Signed update process: solo/signed-updates.md
    - Code documentation: solo/code-overview.md
    - Contributing Code: solo/contributing.md
    - Contributing Docs: solo/documenting.md
    - udev Rules: solo/udev.md
    - About: solo/repo-readme.md

theme:
  name: material
  logo: 'solo/images/logo.svg'
  favicon: 'solo/images/favicon.ico'
