site_name: Solo
site_author: SoloKeys
site_description: 'Documentation for the SoloKeys solo software'
repo_url: 'https://github.com/solokeyssec/solo'
repo_name: 'solokeyssec/solo'
copyright: 'Copyright &copy; 2018 SoloKeys'

nav:
    - Home: index.md
    - README.md: repo-readme.md
    - FIDO2 Implementation: fido2-impl.md
    - Signed update process: signed-updates.md
    - Building: building.md
    - Code documentation: code-overview.md
    - Contributing Code: contributing.md
    - Contributing Docs: documenting.md
    - What the udev?!: udev.md

theme:
  name: material
  logo: 'images/logo.svg'
